jenkins:
  host:  'http://jenkins.example.com'
  port:  '8080'
  token: 'nickisawesome'
  job:   'test'

results:
  host:     'https://results.example.com'
  username: 'admin'
  password: 'changeme'

monolog:
  logfile: develop.log

salt: 'my-salt'

users:
  user1: 'password1'
  user2: 'password2'
